CREATE DATABASE ENROLLMENT;
USE ENROLLMENT;

CREATE TABLE STUDENT(SNUM INT,SNAME VARCHAR(10),MAJOR VARCHAR(20),S_LEVEL VARCHAR(10),AGE INT,PRIMARY KEY(SNUM));

CREATE TABLE FACULTY(FID INT,FNAME VARCHAR(10),DEPT_ID INT,PRIMARY KEY(FID));

CREATE TABLE CLASS(CNAME VARCHAR(10),MEETS_AT TIME,ROOM VARCHAR(10),FID INT,PRIMARY KEY(CNAME),FOREIGN KEY(FID) REFERENCES FACULTY(FID));

CREATE TABLE ENROLL(SNUM INT,CNAME VARCHAR(10),FOREIGN KEY(SNUM) REFERENCES STUDENT(SNUM),FOREIGN KEY(CNAME) REFERENCES CLASS(CNAME));
